### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [iiepdev/mcda-site-classification-educational-facilities#1]
Please adjust links here to point to this 
![Screenshot from 2022-11-02 22-55-26](https://user-images.githubusercontent.com/2510900/199600968-15fbb2f9-547e-46d0-ac62-6f3af5f125bf.png)

**Comment by iiepdev** [comment]
Hi @NyakudyaA  -- thanks for your vigilence! 
I just added the links to the plugin code + QGIS page to the page. In the next few days we will import back the full code here.  
- AAG
